region = "us-east-1"
bucket_name = "jproca-kantox-challenge"
bucket_arn = "arn:aws:s3:::jproca-kantox-challenge"
table_name = "jedi"
lambda_function_name = "json_ingest_lambda"
lambda_runtime = "python3.8"
